-- PostgreSQL schema for the online voting system.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(100) NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    registration_number VARCHAR(50) UNIQUE NOT NULL,
    is_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    position VARCHAR(50) NOT NULL,
    election_year VARCHAR(4) NOT NULL,
    election_date DATE NOT NULL,
    photo VARCHAR(255),
    photo_data BYTEA,
    photo_mime VARCHAR(100),
    biography TEXT,
    manifesto TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE election_settings (
    id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    institution_name VARCHAR(150) NOT NULL DEFAULT 'DIT',
    election_title VARCHAR(200) NOT NULL DEFAULT 'Student Online Voting System',
    starts_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ends_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '30 days'),
    results_visible BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO election_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    candidate_id BIGINT NOT NULL REFERENCES candidates(id),
    position VARCHAR(50) NOT NULL,
    vote_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, position)
);


